darkube_build_trunk-rspsrv-celery_nexfon-staging:
  image: hamravesh.hamdocker.ir/public/darkube-cli:v1.1
  only:
    refs:
    - main
  script:
  - export IMAGE="registry.hamdocker.ir/nexfon/trunk-rspsrv-celery"
  - 'darkube build --push -t $IMAGE:$CI_COMMIT_SHORT_SHA -t $IMAGE:$CI_COMMIT_REF_SLUG  --workdir
    . --file ./DockerfileCelery --build-context . '
  stage: build
darkube_build_trunk-rspsrv_nexfon-staging:
  image: hamravesh.hamdocker.ir/public/darkube-cli:v1.1
  only:
    refs:
    - main
  script:
  - export IMAGE="registry.hamdocker.ir/nexfon/trunk-rspsrv"
  - 'darkube build --push -t $IMAGE:$CI_COMMIT_SHORT_SHA -t $IMAGE:$CI_COMMIT_REF_SLUG  --workdir
    . --file ./Dockerfile --build-context . '
  stage: build
darkube_deploy_trunk-rspsrv-celery_nexfon-staging:
  image: hamravesh.hamdocker.ir/public/darkube-cli:v1.1
  only:
    refs:
    - main
  script:
  - darkube deploy --ref main --token ${DARKUBE_trunk_rspsrv_celery_nexfon_staging_DEPLOY_TOKEN}
    --app-id ${DARKUBE_trunk_rspsrv_celery_nexfon_staging_APP_ID}  --image-tag "${CI_COMMIT_SHORT_SHA}"
    --job-id "${CI_JOB_ID}" --stateless-app true
  stage: deploy
darkube_deploy_trunk-rspsrv_nexfon-staging:
  image: hamravesh.hamdocker.ir/public/darkube-cli:v1.1
  only:
    refs:
    - main
  script:
  - darkube deploy --ref main --token ${DARKUBE_trunk_rspsrv_nexfon_staging_DEPLOY_TOKEN}
    --app-id ${DARKUBE_trunk_rspsrv_nexfon_staging_APP_ID}  --image-tag "${CI_COMMIT_SHORT_SHA}"
    --job-id "${CI_JOB_ID}" --stateless-app true
  stage: deploy
