class ExtensionConfigurations:
    class APILabels:
        CREATE_EXTENSION = "Create extension"
        UPDATE_EXTENSION_PASSWORD = "Update extension password"
        DELETE_EXTENSION = "Delete extension"
        ENABLE_EXTENSION = "Enable extension"
        DISABLE_EXTENSION = "Disable extension"
        ENABLE_CALL_WAITING = "Enable call waiting"
        DISABLE_CALL_WAITING = "Disable call waiting"
        ENABLE_WEB_EXTENSION = "Enable web extension"
        DISABLE_WEB_EXTENSION = "Disable web extension"
        ENABLE_EXTERNAL_CALL = "Enable external call"
        DISABLE_EXTERNAL_CALL = "Disable external call"
        SET_EXTENSION_TO_ENDPOINT = "Set extension to endpoint"
        UNSET_EXTENSION_TO_ENDPOINT = "Unset extension to endpoint"
        UPDATE_EXTENSION_STATUS = "Update extension status"
